(require 'color-theme)

(defun color-theme-nero ()
  (interactive)
  (color-theme-install
   '(color-theme-nero
      ((background-color . "#000000")
      (background-mode . light)
      (border-color . "#222222")
      (cursor-color . "#0573ff")
      (foreground-color . "#cccccc")
      (mouse-color . "#ffffff"))
     (fringe ((t (:background "#303030"))))
     (mode-line ((t (:foreground "#2cb7d8" :background "#111111"))))
     (region ((t (:foreground "#ffffff" :background "#310566"))))
     (font-lock-builtin-face ((t (:foreground "#f500ef"))))
     (font-lock-comment-face ((t (:foreground "#404040"))))
     (font-lock-function-name-face ((t (:foreground "#6ae2bf"))))
     (font-lock-keyword-face ((t (:foreground "#56a4eb"))))
     (font-lock-string-face ((t (:foreground "#978449"))))
     (font-lock-type-face ((t (:foreground"#ad75ea"))))
     (font-lock-variable-name-face ((t (:foreground "#1ed4fa"))))
     (minibuffer-prompt ((t (:foreground "#1f5fa3" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
;;(provide 'nero)
(color-theme-nero)