(add-hook 'shell-mode-hook 'ansi-color-for-comint-mode-on)
(if (eq system-type 'darwin)
    (setenv "PATH" "/usr/local/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin"))
(defalias 'ff 'find-file)
(defalias 'fo 'find-file-other-window)
(defalias 'pj "cd ~/Projetos")
